export enum SystemAgent {
    TREASURY_MINT = 'SYSTEM_TREASURY_MINT',
    PAYSTACK_CLEARING = 'PAYSTACK_CLEARING_CHANNEL',
    FLUTTERWAVE_CLEARING = 'FLUTTERWAVE_CLEARING_CHANNEL',
    STRIPE_CLEARING = 'STRIPE_CLEARING_CHANNEL',
    PAYPAL_CLEARING = 'PAYPAL_CLEARING_CHANNEL',
    CORPORATE_BANK_VAULT = 'PLATFORM_CORPORATE_BANK_VAULT'
}

export const PERMISSIVE_BALANCE_AGENTS: string[] = [
    SystemAgent.TREASURY_MINT,
    SystemAgent.PAYSTACK_CLEARING,
    SystemAgent.FLUTTERWAVE_CLEARING,
    SystemAgent.PAYPAL_CLEARING,
    SystemAgent.STRIPE_CLEARING
];